//This file is licensed under MIT license

console.log("");
console.log("");
console.log("   ======================================================================");
console.log("   |                DEPENDENCIES INSTALLED, NEXT STEPS:                 |");
console.log("   |                                                                    |");
console.log("   |                                                                    |");
console.log("   |1. RUN \"npm run downloadNW\" TO DOWNLOAD AND EXTRACT THE SELECTED    |");
console.log("   |   VERSION OF Nw.JS                                                 |");
console.log("   |                                                                    |");
console.log("   |   (optional) RUN \"npm run applyIcon\" TO CHANGE MAIN EXECUTABLE\'S   |");
console.log("   |   ICON (requires \"ResourceHacker.exe\" on \"Utilities\" directory)    |");
console.log("   |                                                                    |");
console.log("   |2. RUN \"npm run regenerate\" TO GENERATE THE AUTO-GENERATED CODE     |");
console.log("   |                                                                    |");
console.log("   |3. RUN \"npm run build-dev\" TO BUILD THE DEVELOPMENT VERSION         |");
console.log("   |                                                                    |");
console.log("   |4. GO TO THE \"dist/package.nw\" DIRECTORY AND RUN \"npm install\"      |");
console.log("   |   TO INSTALL THE RUNTIME DEPENDENCIES OF THE COMPILED PROJECT      |");
console.log("   |                                                                    |");
console.log("   |5. RUN \"npm run run-nw\" TO RUN THE APPLICATION                      |");
console.log("   |--------------------------------------------------------------------|");
console.log("   |                           OTHER SCRIPTS:                           |");
console.log("   |                                                                    |");
console.log("   |\"npm run build-prod\": BUILDS A PRODUCTION-READY VERSION             |");
console.log("   |\"npm run clean\": CLEAN ALL COMPILED FILES(BINARIES), WITHOUT        |");
console.log("   |                 REMOVING THIRD PART RUNTIME DEPENDENCIES           |");
console.log("   |                 you must run steps 2 and 3 again after this        |");
console.log("   |\"npm run cleanAll\": CLEAN ALL COMPILED FILES(BINARIES), AND         |");
console.log("   |                    RUNTIME DEPENDENCIES, BUT NOT DEVELOPMENT DEPS  |");
console.log("   |                    you must run steps 1, 2, 3 & 4 again after this |");
console.log("   ======================================================================");
console.log("");
console.log("");